---
- name: ensure ca-certificates installed
  become: yes
  apt:
    name: ca-certificates
    state: present

- name: add terminator ppa
  become: yes
  apt_repository:
    repo: 'ppa:gnome-terminator'

- name: install terminator
  become: yes
  apt:
    name: terminator
    state: present
